// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy1ZZjMF7g0euoN005Z_Dr3WDs4qDknlg',
    appId: '1:170226186004:web:3a516efef419178bd4f401',
    messagingSenderId: '170226186004',
    projectId: 'schooley-apk',
    authDomain: 'schooley-apk.firebaseapp.com',
    storageBucket: 'schooley-apk.firebasestorage.app',
    measurementId: 'G-0PQCRHB52E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZhh1_XXQS4z43LuoU_nPZCFRHNBwZzsk',
    appId: '1:170226186004:android:5fbe7a393d47357dd4f401',
    messagingSenderId: '170226186004',
    projectId: 'schooley-apk',
    storageBucket: 'schooley-apk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu2P9Msp5rUdmoWOkwv-zpguGugTmgRNM',
    appId: '1:170226186004:ios:bf4174a6a1002e4cd4f401',
    messagingSenderId: '170226186004',
    projectId: 'schooley-apk',
    storageBucket: 'schooley-apk.firebasestorage.app',
    iosBundleId: 'com.example.schooley',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy1ZZjMF7g0euoN005Z_Dr3WDs4qDknlg',
    appId: '1:170226186004:web:97eb875362034c0cd4f401',
    messagingSenderId: '170226186004',
    projectId: 'schooley-apk',
    authDomain: 'schooley-apk.firebaseapp.com',
    storageBucket: 'schooley-apk.firebasestorage.app',
    measurementId: 'G-QVRGBDKQ7G',
  );
}
